import { describe, expect, test } from "vitest";
import { inferRequestPlan } from "../src/core/request-router.js";
import type { RequestPlan } from "../src/core/request-shape.js";

type ExpectedPlan = Pick<RequestPlan, "intent" | "subject" | "outputShape" | "sources" | "depth" | "execution">;

const prompts = [
  "Inspect this repository and summarize the main architecture, runtime stack, and entry points.",
  "Find the likely cause of this failing test and implement the smallest safe fix.",
  "Add a new REST endpoint for creating projects, following the existing controller/service patterns.",
  "Refactor this large component into smaller components without changing behavior.",
  "Review the current diff as a pull request and call out bugs, regressions, and missing tests.",
  "Add unit tests for the payment validation logic, including edge cases.",
  "Convert this JavaScript file to TypeScript and fix any resulting type errors.",
  "Improve the accessibility of this modal, including keyboard focus and screen reader behavior.",
  "Investigate why this React page rerenders too often and optimize it.",
  "Add pagination to this API endpoint while preserving backward compatibility.",
  "Create a database migration to add a nullable archived_at column and update the model.",
  "Debug this flaky CI failure and explain whether it is test order, timing, or environment related.",
  "Implement optimistic UI updates for this task completion flow.",
  "Add structured logging around the checkout process without logging sensitive data.",
  "Explain how authentication works in this codebase, from login request to session validation.",
  "Replace this deprecated library usage with the recommended modern API.",
  "Add integration tests for the user registration flow.",
  "Find and fix any SQL injection risks in this repository.",
  "Generate OpenAPI documentation for the existing API routes.",
  "Add dark mode support using the project’s existing design tokens.",
  "Investigate this production error stack trace and identify the most likely root cause.",
  "Implement rate limiting for password reset requests.",
  "Update this Dockerfile to reduce image size and improve build caching.",
  "Add input validation to this form and show inline error messages.",
  "Convert this synchronous file processing job to run asynchronously in the background.",
  "Review this database schema and suggest indexes for the slow queries shown here.",
  "Add a feature flag around the new onboarding experience.",
  "Write an end-to-end test for the happy path checkout flow.",
  "Improve the error handling in this GraphQL resolver.",
  "Rename this domain concept across the codebase while keeping migrations safe.",
  "Create a seed script that generates realistic local development data.",
  "Analyze the bundle size and identify the largest avoidable dependencies.",
  "Add retry logic with exponential backoff to this external API client.",
  "Make this page responsive on mobile without changing the desktop layout.",
  "Implement server-side filtering and sorting for this data table.",
  "Find dead code in this package and remove it safely.",
  "Add observability metrics for request latency and error rate.",
  "Explain why this TypeScript generic is failing and simplify it if possible.",
  "Upgrade the project from Node 18 to Node 20 and fix compatibility issues.",
  "Add localization support for this settings page.",
  "Implement a cron job that sends weekly summary emails.",
  "Review this Terraform module for security and maintainability issues.",
  "Add cache invalidation for updated user profile data.",
  "Create a CLI command for importing users from a CSV file.",
  "Fix this race condition in the concurrent job worker.",
  "Add snapshot tests for this UI component only where they provide value.",
  "Implement drag-and-drop reordering for this list.",
  "Investigate why memory usage grows over time in this service.",
  "Add CSRF protection to the session-based routes.",
  "Write developer documentation for running this project locally.",
  "Convert this class-based React component to a function component with hooks.",
  "Add a new column to this admin table with server-provided status values.",
  "Implement soft deletes for organizations and update relevant queries.",
  "Review this API design and suggest a cleaner resource model.",
  "Find all TODO comments related to billing and turn them into actionable issues.",
  "Add a health check endpoint suitable for Kubernetes readiness probes.",
  "Debug why this WebSocket connection disconnects after a few minutes.",
  "Implement file upload with size limits, MIME validation, and progress UI.",
  "Add tests for timezone handling around daylight saving transitions.",
  "Improve this README so a new contributor can be productive in 15 minutes.",
  "Identify security risks in this OAuth callback implementation.",
  "Add graceful shutdown handling to this Node service.",
  "Port this Python script into a reusable package module with tests.",
  "Implement role-based access control for the admin routes.",
  "Review this dependency update PR and identify behavior changes we should test.",
  "Add analytics events for the onboarding funnel.",
  "Fix the layout shift happening when images load on this page.",
  "Create a migration plan for moving from REST to GraphQL for this resource.",
  "Implement idempotency keys for payment creation.",
  "Add validation and helpful errors to this YAML configuration parser.",
  "Investigate why this query is slow and propose a schema or query change.",
  "Build a small internal dashboard showing queue depth and failed jobs.",
  "Add contract tests for this service-to-service API.",
  "Explain this legacy module and identify where a new feature should be added.",
  "Implement infinite scrolling with proper loading, empty, and error states.",
  "Add support for multiple currencies in pricing calculations.",
  "Review this mobile app screen for platform-specific usability issues.",
  "Set up linting and formatting in this repo without causing broad unrelated churn.",
  "Add a mock server for local development against the third-party API.",
  "Fix this failing Docker Compose setup and make the services start reliably.",
  "Implement password strength validation using the existing form framework.",
  "Add audit log entries for permission changes.",
  "Create a small proof of concept for using Web Workers to process large files.",
  "Review this caching strategy and identify stale-data risks.",
  "Add a database transaction around this multi-step write operation.",
  "Generate a changelog from the commits since the last release.",
  "Find inconsistent error response shapes and standardize them.",
  "Add test coverage for this bug before fixing it.",
  "Implement a search box with debounced requests and cancelation of stale calls.",
  "Review this code for accessibility issues related to color contrast and focus states.",
  "Add support for SSO login while keeping password login working.",
  "Investigate why this Kubernetes deployment keeps restarting.",
  "Create a minimal reproduction for this reported frontend bug.",
  "Add schema validation to this event payload before publishing it.",
  "Review this agent tool definition and suggest safer parameter validation.",
  "Implement a rollback-safe migration for splitting a name field into first_name and last_name.",
  "Add Playwright tests for the most important user flows.",
  "Explain the trade-offs between three possible implementations for this feature.",
  "Prepare this branch for a pull request: run tests, summarize changes, and note risks.",
  "Inspect the current worktree, identify unfinished changes, and recommend the next best step."
];

const E = (
  intent: ExpectedPlan["intent"],
  subject: ExpectedPlan["subject"],
  outputShape: ExpectedPlan["outputShape"],
  sources: ExpectedPlan["sources"]
): ExpectedPlan => ({ intent, subject, outputShape, sources, depth: "fast", execution: "plan_only" });

const expected: ExpectedPlan[] = [
  E("extract", "repo", "list", ["local_files"]),
  E("debug", "error", "plan", ["local_files"]),
  E("implement", "api", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("compare", "code", "list", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("debug", "code", "plan", ["local_files"]),
  E("implement", "api", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("debug", "error", "plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("extract", "repo", "paragraph", ["local_files"]),
  E("implement", "package", "patch_plan", ["local_files", "docs", "package_registry"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("debug", "code", "patch_plan", ["local_files"]),
  E("implement", "docs", "structured_data", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("debug", "error", "list", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("compare", "data", "table", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("plan", "repo", "plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("debug", "package", "list", ["local_files", "docs"]),
  E("implement", "api", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "api", "patch_plan", ["local_files"]),
  E("debug", "repo", "plan", ["local_files"]),
  E("implement", "api", "patch_plan", ["local_files", "docs"]),
  E("debug", "code", "paragraph", ["local_files"]),
  E("implement", "package", "patch_plan", ["local_files", "docs", "package_registry"]),
  E("implement", "code", "patch_plan", ["local_files", "docs"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("debug", "code", "list", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("debug", "error", "plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("debug", "error", "plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files", "docs"]),
  E("implement", "docs", "plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("compare", "api", "list", ["local_files"]),
  E("extract", "code", "structured_data", ["local_files"]),
  E("implement", "api", "patch_plan", ["local_files", "docs"]),
  E("debug", "error", "plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files", "docs"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "docs", "plan", ["local_files"]),
  E("debug", "code", "list", ["local_files", "docs"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("compare", "repo", "list", ["local_files", "docs", "package_registry"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("debug", "code", "plan", ["local_files", "docs"]),
  E("plan", "api", "plan", ["local_files", "docs"]),
  E("implement", "api", "patch_plan", ["local_files", "docs"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("debug", "data", "plan", ["local_files", "docs"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "api", "patch_plan", ["local_files", "docs"]),
  E("extract", "code", "paragraph", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files", "docs"]),
  E("compare", "code", "list", ["local_files", "docs"]),
  E("implement", "repo", "patch_plan", ["local_files", "docs"]),
  E("implement", "api", "patch_plan", ["local_files", "docs"]),
  E("debug", "error", "plan", ["local_files", "docs"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files", "docs"]),
  E("compare", "code", "list", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("extract", "repo", "structured_data", ["local_files"]),
  E("implement", "api", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("compare", "code", "list", ["local_files", "docs"]),
  E("implement", "code", "patch_plan", ["local_files", "docs"]),
  E("debug", "error", "plan", ["local_files", "docs"]),
  E("debug", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("compare", "code", "list", ["local_files", "docs"]),
  E("implement", "code", "patch_plan", ["local_files"]),
  E("implement", "code", "patch_plan", ["local_files", "docs"]),
  E("compare", "code", "agent_context", ["local_files"]),
  E("plan", "repo", "plan", ["local_files"]),
  E("extract", "repo", "plan", ["local_files"])
];

describe("request router coding-agent prompt corpus", () => {
  test("classifies the 100 prompt MCP evaluation corpus", () => {
    expect(expected).toHaveLength(prompts.length);

    const mismatches = prompts.flatMap((request, index) => {
      const plan = inferRequestPlan({ request, hints: { depth: "fast", execution: "plan_only" } });
      const actual: ExpectedPlan = {
        intent: plan.intent,
        subject: plan.subject,
        outputShape: plan.outputShape,
        sources: plan.sources,
        depth: plan.depth,
        execution: plan.execution
      };

      return JSON.stringify(actual) === JSON.stringify(expected[index])
        ? []
        : [{ id: index + 1, request, expected: expected[index], actual }];
    });

    expect(mismatches).toEqual([]);
  });
});
